In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
url = 'https://raw.githubusercontent.com/BIKRAM-SAHA/FinalYearProject/main/datasets/EPL_20_21.csv'
df = pd.read_csv(url)

In [3]:
df.shape

(532, 18)

In [4]:
df.head()

,Name,Club,Nationality,Position,Age,Matches,Starts,Mins,Goals,Assists,Passes_Attempted,Perc_Passes_Completed,Penalty_Goals,Penalty_Attempted,xG,xA,Yellow_Cards,Red_Cards
0,Mason Mount,Chelsea,ENG,"MF,FW",21,36,32,2890,6,5,1881,82.3,1,1,0.21,0.24,2,0
1,Edouard Mendy,Chelsea,SEN,GK,28,31,31,2745,0,0,1007,84.6,0,0,0.00,0.00,2,0
2,Timo Werner,Chelsea,GER,FW,24,35,29,2602,6,8,826,77.2,0,0,0.41,0.21,2,0
3,Ben Chilwell,Chelsea,ENG,DF,23,27,27,2286,3,5,1806,78.6,0,0,0.10,0.11,3,0
4,Reece James,Chelsea,ENG,DF,20,32,25,2373,1,2,1987,85.0,0,0,0.06,0.12,3,0

In [5]:
column_names = list(df.columns.values)

In [6]:
column_names

['Name',
 'Club',
 'Nationality',
 'Position',
 'Age',
 'Matches',
 'Starts',
 'Mins',
 'Goals',
 'Assists',
 'Passes_Attempted',
 'Perc_Passes_Completed',
 'Penalty_Goals',
 'Penalty_Attempted',
 'xG',
 'xA',
 'Yellow_Cards',
 'Red_Cards']

In [7]:
df['Position'].unique()

array(['MF,FW', 'GK', 'FW', 'DF', 'MF', 'FW,MF', 'FW,DF', 'DF,MF',
       'MF,DF', 'DF,FW'], dtype=object)

In [8]:
defenders = df.loc[df.Position.str.contains("DF")]

In [9]:
defenders.head()

,Name,Club,Nationality,Position,Age,Matches,Starts,Mins,Goals,Assists,Passes_Attempted,Perc_Passes_Completed,Penalty_Goals,Penalty_Attempted,xG,xA,Yellow_Cards,Red_Cards
3,Ben Chilwell,Chelsea,ENG,DF,23,27,27,2286,3,5,1806,78.6,0,0,0.10,0.11,3,0
4,Reece James,Chelsea,ENG,DF,20,32,25,2373,1,2,1987,85.0,0,0,0.06,0.12,3,0
5,César Azpilicueta,Chelsea,ESP,DF,30,26,24,2188,1,2,2015,87.5,0,0,0.03,0.11,5,1
8,Thiago Silva,Chelsea,BRA,DF,35,23,23,1935,2,0,1871,93.5,0,0,0.05,0.02,5,1
9,Kurt Zouma,Chelsea,FRA,DF,25,24,22,2029,5,0,1720,91.9,0,0,0.08,0.00,3,0

In [10]:
defenders.shape

(218, 18)

In [11]:
midfielders = df.loc[df.Position.str.contains("MF")]

In [12]:
midfielders.head()

,Name,Club,Nationality,Position,Age,Matches,Starts,Mins,Goals,Assists,Passes_Attempted,Perc_Passes_Completed,Penalty_Goals,Penalty_Attempted,xG,xA,Yellow_Cards,Red_Cards
0,Mason Mount,Chelsea,ENG,"MF,FW",21,36,32,2890,6,5,1881,82.3,1,1,0.21,0.24,2,0
6,N'Golo Kanté,Chelsea,FRA,MF,29,30,24,2146,0,2,1504,86.6,0,0,0.04,0.05,7,0
7,Jorginho,Chelsea,ITA,MF,28,28,23,2010,7,1,1739,89.5,7,9,0.31,0.09,2,0
10,Mateo Kovačić,Chelsea,CRO,MF,26,27,21,1815,0,1,1737,91.0,0,0,0.05,0.09,4,0
12,Christian Pulisic,Chelsea,USA,"FW,MF",21,27,18,1738,4,2,690,80.0,0,0,0.28,0.14,2,0

In [13]:
midfielders.shape

(219, 18)

In [14]:
forwards = df.loc[df.Position.str.contains("FW")]

In [15]:
forwards.head()

,Name,Club,Nationality,Position,Age,Matches,Starts,Mins,Goals,Assists,Passes_Attempted,Perc_Passes_Completed,Penalty_Goals,Penalty_Attempted,xG,xA,Yellow_Cards,Red_Cards
0,Mason Mount,Chelsea,ENG,"MF,FW",21,36,32,2890,6,5,1881,82.3,1,1,0.21,0.24,2,0
2,Timo Werner,Chelsea,GER,FW,24,35,29,2602,6,8,826,77.2,0,0,0.41,0.21,2,0
12,Christian Pulisic,Chelsea,USA,"FW,MF",21,27,18,1738,4,2,690,80.0,0,0,0.28,0.14,2,0
13,Kai Havertz,Chelsea,GER,"MF,FW",21,27,18,1520,4,3,765,86.1,0,0,0.37,0.09,2,0
15,Hakim Ziyech,Chelsea,MAR,"FW,MF",27,23,15,1172,2,3,734,74.7,0,0,0.15,0.28,3,0

In [16]:
forwards.shape

(176, 18)

In [17]:
goalkeepers = df.loc[df.Position.str.contains("GK")]

In [18]:
goalkeepers.head()

,Name,Club,Nationality,Position,Age,Matches,Starts,Mins,Goals,Assists,Passes_Attempted,Perc_Passes_Completed,Penalty_Goals,Penalty_Attempted,xG,xA,Yellow_Cards,Red_Cards
1,Edouard Mendy,Chelsea,SEN,GK,28,31,31,2745,0,0,1007,84.6,0,0,0.0,0.00,2,0
20,Kepa Arrizabalaga,Chelsea,ESP,GK,25,7,6,585,0,0,243,81.5,0,0,0.0,0.00,1,0
22,Willy Caballero,Chelsea,ARG,GK,38,1,1,90,0,0,26,92.3,0,0,0.0,0.00,0,0
27,Ederson,Manchester City,BRA,GK,26,36,36,3240,0,1,1090,83.1,0,0,0.0,0.01,3,0
48,Scott Carson,Manchester City,ENG,GK,34,1,1,90,0,0,16,93.8,0,0,0.0,0.00,0,0

In [19]:
goalkeepers.shape

(42, 18)